services:
  database_finapi:
    image: postgres:14-alpine
    container_name: database_finapi
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=finapi
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: